export interface TownData {
  name: string;
  slug: string;
  county: "Suffolk" | "Nassau";
  countyPage: string;
  region: "north-shore" | "south-shore" | "east-end" | "north-fork" | "nassau-suburban" | "nassau-north" | "nassau-south";
  intro: string;
  whyHere: string;
  areas: string[];
  nearbyTowns: string[];
}

export const REGION_CONTENT: Record<string, {
  regionLabel: string;
  tickHabitatIntro: string;
  tickHabitats: string[];
  alertTitle: string;
  alertText: string;
  seasonNote: string;
  faqQ: string;
  faqA: string;
}> = {
  "north-shore": {
    regionLabel: "North Shore Suffolk County",
    tickHabitatIntro: "North Shore properties have some of the highest tick pressure on Long Island due to dense tree canopy, shaded property edges, active deer corridors, and proximity to wooded bluffs and nature preserves.",
    tickHabitats: [
      "Wooded property edges and tree lines",
      "Leaf litter under mature oak and maple trees",
      "Ornamental shrub and mulch beds bordering the lawn",
      "Shaded areas with deer movement corridors",
      "Ground cover and pachysandra beds",
      "Stone walls and brush piles adjacent to woods",
    ],
    alertTitle: "High Deer Tick Pressure — North Shore",
    alertText: "North Shore communities consistently show elevated tick pressure due to large deer populations, wooded bluffs, and shaded lots. Barrier treatments are most effective when started early in the season — March or April — before the May–June nymph peak.",
    seasonNote: "Tick activity on the North Shore begins as early as March and can continue through November. The highest risk windows are May–June (nymph season) and September–October (adult deer tick fall peak).",
    faqQ: "Why are ticks worse on the North Shore than in other parts of Long Island?",
    faqA: "The North Shore has a combination of factors that concentrate tick populations: wooded bluffs and ravines, high deer density, mature tree canopy that keeps leaves and ground cover moist, and residential lots that often border preserved woodland. These conditions are ideal for blacklegged (deer) tick survival and reproduction.",
  },
  "south-shore": {
    regionLabel: "South Shore Suffolk County",
    tickHabitatIntro: "South Shore communities face tick pressure in residential landscaping, coastal grassy areas, and yards adjacent to parks and preserved land. The humid coastal climate extends tick activity through the season.",
    tickHabitats: [
      "Lawn edges adjacent to grassy fields or parkland",
      "Ornamental plantings and mulch beds",
      "Coastal grassy and marshy border areas",
      "Dog walking routes and recreational areas",
      "Shrub beds along property perimeters",
      "Leaf litter in shaded sections of yards",
    ],
    alertTitle: "Coastal Humidity Extends Tick Season",
    alertText: "South Shore communities experience elevated humidity from proximity to the bay and ocean, which can extend tick survival and activity into periods when inland yards see lower pressure. Don't assume suburban or coastal yards carry lower risk.",
    seasonNote: "Tick season on the South Shore runs from early spring through late fall. Humid summer conditions can sustain tick populations in residential yards even in areas without deep woodland.",
    faqQ: "Do South Shore yards have lower tick risk than wooded North Shore properties?",
    faqA: "Not necessarily. While deep-woods exposure is higher on the North Shore, South Shore yards still carry significant tick risk — especially in mulch beds, ornamental plantings, and yard edges adjacent to parks or grassy areas. Deer ticks don't need forests; they thrive in shaded residential landscaping.",
  },
  "east-end": {
    regionLabel: "East End / Hamptons",
    tickHabitatIntro: "East End properties — including the Hamptons — often feature large lots, wooded edges, mature landscaping, and significant deer and wildlife pressure. These conditions create elevated tick exposure across all property types.",
    tickHabitats: [
      "Wooded lot perimeters and tree lines",
      "Deer trails crossing through or adjacent to the property",
      "Ornamental gardens, hedgerows, and mulch beds",
      "Ground cover plantings under mature trees",
      "Brush edges along driveways and walking paths",
      "Wooded buffers between neighboring properties",
    ],
    alertTitle: "High Wildlife Pressure — East End",
    alertText: "The East End has one of the highest deer densities on Long Island. Combined with large lot sizes, mature wooded edges, and preserved land nearby, tick exposure on East End properties is significant from early spring through late fall. Seasonal residents should schedule treatment before occupying the property.",
    seasonNote: "Tick season on the East End mirrors the rest of Long Island — May–June nymph peak and September–October adult peak — but deer density and lot size can mean higher exposure across the full season.",
    faqQ: "Should seasonal residents treat their East End property if they're not there year-round?",
    faqA: "Yes. Ticks remain active whether or not the property is occupied. A pre-season barrier treatment in April or May protects the property before you arrive. Returning to an untreated yard with high deer traffic can mean significant tick exposure on arrival.",
  },
  "north-fork": {
    regionLabel: "North Fork / East End",
    tickHabitatIntro: "The North Fork combines agricultural land, wooded edges, and active deer populations that create year-round tick pressure across both residential and rural properties.",
    tickHabitats: [
      "Wooded borders between farm fields and residential lots",
      "Deer corridors running through rural properties",
      "Ornamental plantings and shaded yard edges",
      "Ground cover under mature trees",
      "Brush and hedgerow borders",
      "Leaf litter adjacent to fields or preserves",
    ],
    alertTitle: "Rural Properties — North Fork",
    alertText: "North Fork properties often border agricultural land or preserved open space, which supports high deer and wildlife populations that carry ticks onto residential yards. Barrier treatments along property edges are especially important on rural lots.",
    seasonNote: "Tick activity on the North Fork begins in early spring and runs through late fall. Properties with deer movement from adjacent fields or preserves may see higher than average pressure across the full season.",
    faqQ: "Do agricultural or rural properties on the North Fork have higher tick risk?",
    faqA: "Yes. Properties adjacent to farm fields, vineyards, or open preserves on the North Fork tend to see higher tick pressure because deer and wildlife freely move between open land and residential yards. The property edges — mulch beds, shrub lines, lawn perimeters — are the primary treatment zones.",
  },
  "nassau-suburban": {
    regionLabel: "Nassau County",
    tickHabitatIntro: "Nassau County's suburban yards carry more tick risk than most homeowners expect. Ticks shelter in ornamental plantings, mulch beds, leaf litter, and yard edges — they don't require deep woods.",
    tickHabitats: [
      "Ornamental shrub beds and foundation plantings",
      "Mulch borders around trees and gardens",
      "Leaf litter under mature trees",
      "Lawn perimeter edges adjacent to neighbors' landscaping",
      "Dog walking paths and play areas",
      "Shaded areas with low light penetration",
    ],
    alertTitle: "Suburban Tick Risk — Nassau County",
    alertText: "Ticks are established throughout Nassau County — including heavily landscaped suburban neighborhoods. Properties with mature trees, ornamental beds, and shaded areas carry meaningful tick risk even without adjacent woods. Pets and children are often the first to encounter ticks.",
    seasonNote: "Tick season in Nassau County runs spring through fall. The May–June nymph peak is the highest-risk window — nymphs are tiny, hard to see, and responsible for most Lyme disease cases.",
    faqQ: "I live in a suburban Nassau County neighborhood — do I really need tick control?",
    faqA: "Yes. Ticks do not require forests. In Nassau County, deer tick populations are well established in residential areas — particularly in ornamental plantings, mulch beds, and shaded yard edges. Many Nassau homeowners are surprised to find ticks on their properties despite having no woods nearby.",
  },
  "nassau-north": {
    regionLabel: "Nassau County North Shore",
    tickHabitatIntro: "The Nassau North Shore — including communities like Manhasset, Great Neck, and Roslyn — combines mature tree canopy, wooded property edges, and active deer populations that create elevated tick pressure compared to inland Nassau communities.",
    tickHabitats: [
      "Mature wooded property edges and tree lines",
      "Leaf litter under established oaks and maples",
      "Ornamental beds and mulch borders",
      "Deer movement corridors through residential streets",
      "Ground cover and shade plantings",
      "Shaded drainage areas and landscape buffers",
    ],
    alertTitle: "Elevated Pressure — Nassau North Shore",
    alertText: "Nassau North Shore communities have higher tick pressure than much of Nassau due to larger lots, older tree canopy, and deer movement from adjacent preserved land. Barrier treatments targeting property edges and ornamental beds are most effective.",
    seasonNote: "Tick activity on the Nassau North Shore follows the same pattern as the rest of Long Island — peak risk in May–June and September–October — but elevated deer density can mean pressure throughout the season.",
    faqQ: "Why is tick pressure higher on the Nassau North Shore?",
    faqA: "Nassau North Shore communities like Manhasset, Great Neck, and Roslyn tend to have larger lots, mature tree canopy, and proximity to preserved greenspace that supports deer populations. Deer carry adult ticks into residential areas, dropping them on lawns, ornamental beds, and property edges.",
  },
  "nassau-south": {
    regionLabel: "Nassau County South Shore",
    tickHabitatIntro: "Nassau South Shore communities carry tick risk in residential landscaping, park-adjacent yards, and coastal edges. The humid coastal climate can extend tick survival compared to drier inland areas.",
    tickHabitats: [
      "Lawn edges adjacent to parks or preserved land",
      "Ornamental plantings and mulch beds",
      "Coastal grassy edges and marshy areas",
      "Pet exercise areas and dog-walking routes",
      "Shaded areas with leaf litter",
      "Foundation plantings around structures",
    ],
    alertTitle: "South Shore Humidity Extends Tick Activity",
    alertText: "Proximity to the bay and ocean creates humidity that helps ticks survive in residential landscaping longer into the season. Nassau South Shore homeowners — especially those near parks or water — should not assume low tick risk based on their suburban setting.",
    seasonNote: "Tick season on the Nassau South Shore runs from spring through fall. Humid coastal conditions can sustain tick activity in ornamental beds and yard edges through the full warm-weather season.",
    faqQ: "Are South Shore Nassau yards at lower risk than other areas?",
    faqA: "No. While South Shore Nassau neighborhoods may appear fully suburban, ticks are well established in the region's ornamental beds, lawn edges, and shaded plantings. Coastal humidity helps ticks persist in residential landscapes even without deep woodland nearby.",
  },
};

export const TOWNS: TownData[] = [
  // North Shore
  {
    name: "Smithtown",
    slug: "smithtown",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "north-shore",
    intro: "Smithtown sits at the heart of the North Shore, with wooded neighborhoods, mature tree canopy, and extensive deer movement through residential streets and adjacent preserves. Tick pressure in Smithtown is among the highest on Long Island — particularly in properties bordering Blydenburgh County Park and wooded stream corridors.",
    whyHere: "Smithtown's combination of older wooded lots, active deer populations, and proximity to county parkland creates ideal conditions for blacklegged (deer) tick populations. The town's shaded, leaf-litter-rich yards provide the moisture and cover ticks need to survive and reproduce.",
    areas: ["Blydenburgh County Park borders", "Nissequogue River areas", "Kings Park adjacent neighborhoods", "Hauppauge Road corridors", "St. James border areas"],
    nearbyTowns: ["huntington", "northport", "commack", "kings-park", "stony-brook"],
  },
  {
    name: "Huntington",
    slug: "huntington",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "north-shore",
    intro: "Huntington is one of the largest towns on Long Island's North Shore, encompassing wooded inland neighborhoods, harbor-adjacent properties, and areas bordering Caumsett State Park and Cold Spring Harbor State Park. Tick pressure varies across the town but is consistently elevated in wooded and park-adjacent areas.",
    whyHere: "Huntington's diverse landscape — from harbor communities to inland wooded lots — supports high deer populations that carry ticks throughout the town. Properties near Caumsett, Cold Spring Harbor, and the Huntington Hills area have particularly high tick exposure due to dense woodland and active deer movement.",
    areas: ["Caumsett State Park border areas", "Cold Spring Harbor adjacent neighborhoods", "Lloyd Neck communities", "Dix Hills wooded properties", "West Hills and Melville borders"],
    nearbyTowns: ["northport", "smithtown", "commack", "cold-spring-harbor", "centerport"],
  },
  {
    name: "Northport",
    slug: "northport",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "north-shore",
    intro: "Northport's North Shore location — with its harbor, wooded bluffs, and residential neighborhoods bordering undeveloped land — creates significant tick pressure throughout the village and surrounding community. Properties near Northport Harbor and the surrounding wooded areas see consistent deer tick activity from early spring through late fall.",
    whyHere: "Northport's wooded bluffs, harbor-adjacent greenery, and proximity to Caumsett State Park create corridors for deer movement into residential areas. Many Northport properties have shaded lots with significant leaf litter and ornamental plantings — ideal tick harborage.",
    areas: ["Northport Harbor adjacent streets", "Woodhull Landing area", "Eaton's Neck communities", "Crab Meadow area", "Fort Salonga border neighborhoods"],
    nearbyTowns: ["huntington", "smithtown", "centerport", "fort-salonga", "kings-park"],
  },
  {
    name: "Commack",
    slug: "commack",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "north-shore",
    intro: "Commack is a densely residential North Shore community that borders Blydenburgh County Park and carries tick pressure throughout its wooded and suburban neighborhoods. Many Commack homeowners are surprised to encounter ticks in maintained yards — ticks thrive in ornamental plantings and mulch beds regardless of how manicured the surrounding lawn is.",
    whyHere: "Commack sits adjacent to significant preserved land including Blydenburgh County Park, and deer regularly transit through residential neighborhoods. The combination of mature landscaping, mulch beds, and shaded lots throughout Commack provides consistent tick harborage.",
    areas: ["Blydenburgh County Park border streets", "Hobart Road and Jericho Turnpike corridors", "Veteran's Memorial Highway neighborhoods", "Kings Park Road adjacent properties", "Hauppauge border areas"],
    nearbyTowns: ["smithtown", "huntington", "hauppauge", "kings-park", "dix-hills"],
  },
  {
    name: "Stony Brook",
    slug: "stony-brook",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "north-shore",
    intro: "Stony Brook is a North Shore community known for its historic harbor, university campus, and wooded residential neighborhoods. The area's mature tree canopy, proximity to the harbor, and extensive wooded lots create ideal conditions for year-round tick pressure — particularly for blacklegged deer ticks.",
    whyHere: "Stony Brook's mix of wooded harbor-adjacent properties, university preserve land, and mature residential neighborhoods supports elevated deer tick populations. The area's leaf-litter-rich yards, shaded lots, and deer corridors running from harbor to inland preserve make it one of the higher-pressure North Shore communities.",
    areas: ["Stony Brook Harbor adjacent streets", "Frank Melville Memorial Park area", "University campus border neighborhoods", "Avalon Nature Preserve vicinity", "Old Field Road communities"],
    nearbyTowns: ["setauket", "port-jefferson", "miller-place", "mount-sinai", "smithtown"],
  },
  {
    name: "Setauket",
    slug: "setauket",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "north-shore",
    intro: "Setauket — including both East Setauket and Setauket proper — is a historic North Shore community with wooded lots, a scenic harbor, and residential neighborhoods that see consistent high tick pressure. The area's combination of mature landscape, deer movement, and preserved land creates year-round tick exposure for homeowners.",
    whyHere: "Setauket's wooded residential character, proximity to Old Field and Conscience Bay, and active deer populations make it one of the higher-risk North Shore tick areas. Many properties have shaded yards with significant leaf litter, ornamental beds, and lawn edges adjacent to wooded buffers.",
    areas: ["Conscience Bay area", "Old Field adjacent neighborhoods", "Setauket Harbor vicinity", "Frank Melville Memorial Park borders", "Gnarled Hollow Road communities"],
    nearbyTowns: ["stony-brook", "port-jefferson", "mount-sinai", "miller-place", "brookhaven"],
  },
  {
    name: "Port Jefferson",
    slug: "port-jefferson",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "north-shore",
    intro: "Port Jefferson — including Port Jefferson Station — is a North Shore harbor community where wooded bluffs, harbor-adjacent properties, and deer-heavy corridors create persistent tick pressure. Residents on the village's elevated wooded streets and the surrounding Station area both see consistent tick activity through the season.",
    whyHere: "Port Jefferson's harbor setting, wooded bluffs, and density of mature trees throughout the village create shaded, moist conditions ideal for tick survival. Deer move freely between the wooded hillsides above the harbor and residential neighborhoods, depositing ticks into yards and ornamental plantings.",
    areas: ["Port Jefferson Harbor adjacent streets", "Wooded bluff neighborhoods above the village", "Port Jefferson Station residential areas", "Mount Sinai border communities", "Belle Terre vicinity"],
    nearbyTowns: ["stony-brook", "setauket", "mount-sinai", "miller-place", "belle-terre"],
  },
  {
    name: "Miller Place",
    slug: "miller-place",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "north-shore",
    intro: "Miller Place is a North Shore community with a mix of residential neighborhoods and wooded properties, located between Port Jefferson and Rocky Point. Deer populations in the area are significant, and tick pressure throughout Miller Place — particularly in properties near wooded edges and undeveloped land — is consistently elevated.",
    whyHere: "Miller Place sits in a corridor of North Shore suburban development surrounded by wooded areas and protected land. Deer movement through residential neighborhoods is common, bringing ticks into yards, ornamental beds, and lawn perimeters throughout the season.",
    areas: ["Miller Place Harbor adjacent areas", "Rocky Point border neighborhoods", "Sound Avenue corridor properties", "North Country Road communities", "Wildwood State Park vicinity"],
    nearbyTowns: ["mount-sinai", "port-jefferson", "stony-brook", "rocky-point", "sound-beach"],
  },
  {
    name: "Mount Sinai",
    slug: "mount-sinai",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "north-shore",
    intro: "Mount Sinai is a North Shore community known for its harbor, wooded neighborhoods, and proximity to the Long Island Sound. The area's tree canopy, residential lots bordering wooded preserves, and active deer populations create significant tick pressure for homeowners throughout the spring and fall seasons.",
    whyHere: "Mount Sinai Harbor and the surrounding wooded residential areas provide ideal tick habitat — shaded lots, leaf litter, and ornamental plantings adjacent to deer movement corridors. The area's position between Crystal Brook Hollow State Park and Mount Sinai Harbor concentrates deer and tick activity.",
    areas: ["Mount Sinai Harbor vicinity", "Crystal Brook Hollow State Park border areas", "North Country Road properties", "Sound Beach adjacent neighborhoods", "Miller Place border communities"],
    nearbyTowns: ["miller-place", "port-jefferson", "setauket", "stony-brook", "sound-beach"],
  },
  // South Shore
  {
    name: "Brookhaven",
    slug: "brookhaven",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "south-shore",
    intro: "Brookhaven — the largest town in New York State by area — spans from the North Shore to the South Shore and contains a remarkable range of environments. South Shore Brookhaven communities, including Bellport and East Patchogue, see tick pressure in residential yards adjacent to coastal marshes, parks, and preserved land.",
    whyHere: "Brookhaven's vast size encompasses everything from North Shore wooded bluffs to South Shore coastal neighborhoods. South Shore areas carry tick pressure from coastal humidity, grassy edges adjacent to fire island inlets, and residential yards near Bellport Bay and Patchogue Bay.",
    areas: ["Bellport Bay adjacent neighborhoods", "East Patchogue residential areas", "Brookhaven State Park border communities", "Yaphank and Medford areas", "Gordon Heights and Coram neighborhoods"],
    nearbyTowns: ["islip", "sayville", "bay-shore", "riverhead", "setauket"],
  },
  {
    name: "Islip",
    slug: "islip",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "south-shore",
    intro: "The Town of Islip encompasses Bay Shore, Sayville, and many South Shore communities with yards that back up to coastal areas, parks, and residential greenways. Tick pressure in Islip town communities is consistent throughout the season, particularly in properties adjacent to the Great South Bay shoreline and local parks.",
    whyHere: "South Shore Islip communities see tick pressure in residential landscaping, coastal grassy areas, and yards bordering the Great South Bay. The humid coastal climate extends tick survival, and residential areas adjacent to Connetquot River State Park and other preserved land see elevated deer movement.",
    areas: ["Great South Bay adjacent communities", "Connetquot River State Park border neighborhoods", "Heckscher State Park vicinity", "Baxter Estates and Bay Shore waterfront areas", "Central Islip and Brentwood residential areas"],
    nearbyTowns: ["babylon", "sayville", "bay-shore", "brookhaven", "smithtown"],
  },
  {
    name: "Babylon",
    slug: "babylon",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "south-shore",
    intro: "Babylon — including the villages of Amityville, North Babylon, West Babylon, and Lindenhurst — is a South Shore town where residential neighborhoods carry tick pressure in ornamental beds, park-adjacent yards, and coastal edges. The Great South Bay shoreline and Belmont Lake State Park create corridors for deer and tick movement into residential areas.",
    whyHere: "Babylon town's South Shore location, coastal marshes, and proximity to Belmont Lake State Park and Robert Moses State Park create conditions for tick activity in residential neighborhoods. The humid bay environment supports tick survival in suburban landscaping throughout the season.",
    areas: ["Belmont Lake State Park border neighborhoods", "Amityville Harbor adjacent streets", "North Babylon residential areas", "Lindenhurst canal communities", "West Babylon park-adjacent neighborhoods"],
    nearbyTowns: ["islip", "bay-shore", "sayville", "massapequa", "lindenhurst"],
  },
  {
    name: "Sayville",
    slug: "sayville",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "south-shore",
    intro: "Sayville is a South Shore community known for its ferry access to Fire Island and its bay-adjacent residential neighborhoods. Tick pressure in Sayville is steady throughout the season, particularly in properties near the bay, local parks, and residential landscaping adjacent to grassy edges.",
    whyHere: "Sayville's position along the Great South Bay, combined with local parks and residential greenways, creates consistent tick habitat in suburban yards. The coastal humidity and grassy marsh edges near the shoreline support tick activity, and residential ornamental beds throughout the village are prime harborage zones.",
    areas: ["Sayville waterfront neighborhoods", "Connetquot River State Park border areas", "Cherry Grove and bay ferry landing vicinity", "West Sayville residential streets", "Bohemia adjacent communities"],
    nearbyTowns: ["islip", "bay-shore", "brookhaven", "patchogue", "west-sayville"],
  },
  {
    name: "Bay Shore",
    slug: "bay-shore",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "south-shore",
    intro: "Bay Shore is a South Shore community with active residential neighborhoods, ferry access to Fire Island, and yards that sit adjacent to the Great South Bay. Tick pressure in Bay Shore is consistent — particularly in landscaped yards, park-edge properties, and areas near Heckscher State Park.",
    whyHere: "Bay Shore's combination of residential landscaping, coastal humidity, and proximity to Heckscher State Park and the Great South Bay creates conditions that support tick activity in suburban yards. Deer move through residential corridors and deposit ticks in ornamental beds, mulch borders, and lawn edges.",
    areas: ["Heckscher State Park border neighborhoods", "Bay Shore waterfront streets", "Brightwaters residential areas", "Penataquit Point vicinity", "Brentwood border communities"],
    nearbyTowns: ["islip", "babylon", "sayville", "brentwood", "west-islip"],
  },
  // East End
  {
    name: "Riverhead",
    slug: "riverhead",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "east-end",
    intro: "Riverhead sits at the fork of Long Island's East End, where the North Fork and South Fork diverge. The town encompasses a mix of agricultural land, suburban neighborhoods, and wooded edges — with tick pressure from deer populations that move freely between open land and residential properties.",
    whyHere: "Riverhead's agricultural setting and position at the head of the Peconic Bay means deer and wildlife move between farm fields, vineyards, and residential neighborhoods. Properties bordering open land, wooded edges, and the Peconic Riverhead corridor see consistent tick pressure throughout the season.",
    areas: ["Peconic River corridor properties", "Agricultural land border neighborhoods", "Calverton and Manorville areas", "Wading River adjacent communities", "Riverhead town center residential areas"],
    nearbyTowns: ["southold", "southampton", "wading-river", "calverton", "manorville"],
  },
  {
    name: "Southampton",
    slug: "southampton",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "east-end",
    intro: "Southampton encompasses both the historic village and the broader town across the South Fork, including Westhampton, Hampton Bays, and communities along the ocean and bay. Large lots, wooded edges, and significant deer pressure make Southampton town one of the higher-risk areas for tick exposure on Long Island.",
    whyHere: "Southampton's large residential lots, wooded buffers, and extensive deer populations create significant tick pressure throughout the town. Properties with wooded edges, mature landscaping, and proximity to The Nature Conservancy preserves and the Peconic Estuary see elevated tick activity from spring through fall.",
    areas: ["Southampton Village adjacent neighborhoods", "Westhampton Beach residential areas", "Hampton Bays waterfront communities", "Water Mill and Bridgehampton borders", "Quogue and East Quogue residential areas"],
    nearbyTowns: ["east-hampton", "riverhead", "westhampton", "hampton-bays", "quogue"],
  },
  {
    name: "East Hampton",
    slug: "east-hampton",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "east-end",
    intro: "East Hampton — encompassing the village, Amagansett, Springs, Montauk, and surrounding communities — is known for its large properties, mature wooded edges, and high deer populations. Tick pressure throughout the East Hampton area is significant and has been for decades, making professional barrier treatment an important part of seasonal property care.",
    whyHere: "East Hampton has some of the highest deer density on Long Island, which directly correlates to tick pressure. Large lots with wooded edges, proximity to the Long Island National Wildlife Refuge, and the area's historic wooded character create ideal conditions for blacklegged tick populations throughout the season.",
    areas: ["Springs residential neighborhoods", "Amagansett village and surroundings", "Northwest Harbor adjacent properties", "Napeague Harbor area", "Three Mile Harbor and Cedar Point vicinity"],
    nearbyTowns: ["southampton", "southold", "shelter-island", "amagansett", "montauk"],
  },
  {
    name: "Southold",
    slug: "southold",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "north-fork",
    intro: "Southold is the North Fork's largest town, stretching from Cutchogue and Mattituck to Greenport and Orient Point. The area's combination of agricultural land, wooded residential lots, vineyards, and active deer populations creates consistent tick pressure for homeowners across the North Fork.",
    whyHere: "Southold's North Fork setting — where farm fields, wooded buffers, and residential neighborhoods all border each other — creates ideal conditions for tick proliferation. Deer movement from agricultural open land into residential yards brings ticks to properties throughout the town.",
    areas: ["Cutchogue residential neighborhoods", "Mattituck agricultural border properties", "Greenport village adjacent areas", "Orient Point communities", "Peconic Bay waterfront neighborhoods"],
    nearbyTowns: ["east-hampton", "shelter-island", "riverhead", "mattituck", "greenport"],
  },
  {
    name: "Shelter Island",
    slug: "shelter-island",
    county: "Suffolk",
    countyPage: "/tick-spraying-suffolk-county",
    region: "east-end",
    intro: "Shelter Island — accessible only by ferry — has one of the highest tick densities in New York State. The island's protected forests, Mashomack Nature Preserve, and significant deer population combine to make tick exposure a serious concern for all residents and seasonal visitors.",
    whyHere: "Shelter Island's tick problem is well documented and severe. With a third of the island protected as Mashomack Preserve, deer populations are high, and blacklegged tick pressure is among the heaviest in the region. Nearly every property on the island — regardless of size or landscaping — experiences meaningful tick exposure.",
    areas: ["Mashomack Preserve border properties", "Shelter Island Heights residential streets", "Ram Island communities", "North Haven peninsula properties", "West Neck Harbor area neighborhoods"],
    nearbyTowns: ["southold", "east-hampton", "north-haven", "greenport", "sag-harbor"],
  },
  // Nassau
  {
    name: "Garden City",
    slug: "garden-city",
    county: "Nassau",
    countyPage: "/tick-spraying-nassau-county",
    region: "nassau-suburban",
    intro: "Garden City is an established Nassau County community with mature landscaping, tree-lined streets, and residential yards that carry tick risk in ornamental plantings, mulch beds, and shaded lawn edges. Pestify serves Garden City homeowners with targeted barrier treatments designed for suburban Nassau County properties.",
    whyHere: "Garden City's mature urban tree canopy and extensive ornamental landscaping provide harborage for ticks in residential yards throughout the community. While the area is fully suburban, ticks are well established in the leaf litter, mulch beds, and shaded edges of well-landscaped Garden City properties.",
    areas: ["Cathedral Avenue residential neighborhoods", "Old Garden City residential streets", "Garden City South adjacent areas", "Stewart Avenue corridor properties", "Meadowbrook Parkway adjacent communities"],
    nearbyTowns: ["garden-city-south", "hempstead", "mineola", "east-garden-city", "uniondale"],
  },
  {
    name: "Manhasset",
    slug: "manhasset",
    county: "Nassau",
    countyPage: "/tick-spraying-nassau-county",
    region: "nassau-north",
    intro: "Manhasset is a Nassau North Shore community with large lots, mature tree canopy, and properties that border Manhasset Bay and wooded residential streets. Tick pressure in Manhasset is higher than in much of Nassau due to the area's established tree cover, deer movement, and affluent residential landscaping.",
    whyHere: "Manhasset's North Shore Nassau location brings it closer to the tick pressure patterns of the Long Island North Shore. Large lots with established shade trees, ornamental plantings, and proximity to Manhasset Bay create conditions that support deer tick activity throughout the season.",
    areas: ["Manhasset Bay adjacent streets", "Plandome Road neighborhoods", "Flower Hill residential areas", "Munsey Park community", "Saddle Rock adjacent properties"],
    nearbyTowns: ["great-neck", "roslyn", "port-washington", "great-neck-plaza", "flower-hill"],
  },
  {
    name: "Great Neck",
    slug: "great-neck",
    county: "Nassau",
    countyPage: "/tick-spraying-nassau-county",
    region: "nassau-north",
    intro: "Great Neck is a North Shore Nassau peninsula with numerous villages, mature residential neighborhoods, and properties adjacent to Long Island Sound inlets and wooded greenways. Tick pressure in Great Neck is consistent, particularly in larger lots and properties near the water and wooded edges.",
    whyHere: "Great Neck's peninsular North Shore Nassau location, mature tree canopy, and active deer population create tick risk throughout the area's residential neighborhoods. Properties near Steppingstone Park, King's Point, and the Sound inlets see elevated pressure from deer moving between water-adjacent greenspace and suburban yards.",
    areas: ["Kings Point residential communities", "Steppingstone Park vicinity", "Great Neck Plaza adjacent neighborhoods", "Saddle Rock and Kensington areas", "Thomaston and Russell Gardens communities"],
    nearbyTowns: ["manhasset", "roslyn", "port-washington", "kings-point", "lake-success"],
  },
  {
    name: "Roslyn",
    slug: "roslyn",
    county: "Nassau",
    countyPage: "/tick-spraying-nassau-county",
    region: "nassau-north",
    intro: "Roslyn — including Roslyn Heights, Roslyn Harbor, and East Hills — is a Nassau North Shore community with established residential neighborhoods, wooded hillsides, and properties that border Hempstead Harbor. Tick pressure in the Roslyn area is meaningful, particularly in yards with mature trees and ornamental plantings.",
    whyHere: "Roslyn's Nassau North Shore setting, combined with the area's established wooded character and Hempstead Harbor views, creates conditions that support tick activity in residential yards. Deer move through the area from adjacent wooded corridors, and ornamental plantings throughout Roslyn's mature neighborhoods provide consistent tick harborage.",
    areas: ["Roslyn Harbor waterfront streets", "East Hills residential neighborhoods", "Roslyn Heights community areas", "Old Westbury adjacent properties", "Albertson border communities"],
    nearbyTowns: ["manhasset", "great-neck", "port-washington", "old-westbury", "east-hills"],
  },
  {
    name: "Plainview",
    slug: "plainview",
    county: "Nassau",
    countyPage: "/tick-spraying-nassau-county",
    region: "nassau-suburban",
    intro: "Plainview is an established Nassau County community where residential yards, mature landscaping, and park-adjacent properties carry consistent tick risk. Pestify treats Plainview homes with targeted barrier applications to ornamental beds, mulch borders, and shaded yard edges where ticks are most commonly found.",
    whyHere: "Plainview's mature suburban landscaping and proximity to Old Bethpage Village Restoration and Bethpage State Park create corridors for deer movement into residential neighborhoods. Ticks established in the area's leaf litter, mulch beds, and shaded foundation plantings are easily encountered by children and pets in treated yards.",
    areas: ["Bethpage State Park border neighborhoods", "Old Bethpage adjacent communities", "Woodbury Road residential areas", "Old Country Road corridor properties", "Farmingdale border neighborhoods"],
    nearbyTowns: ["syosset", "bethpage", "old-bethpage", "woodbury", "hicksville"],
  },
  {
    name: "Massapequa",
    slug: "massapequa",
    county: "Nassau",
    countyPage: "/tick-spraying-nassau-county",
    region: "nassau-south",
    intro: "Massapequa — including Massapequa Park and North Massapequa — is a South Shore Nassau community where residential neighborhoods border Massapequa Preserve, the South Oyster Bay wetlands, and the Great South Bay. Tick pressure in the Massapequa area is elevated compared to inland Nassau due to the preserve and coastal setting.",
    whyHere: "Massapequa Preserve is a significant wildlife corridor that runs directly through the community, supporting deer populations that bring ticks into residential yards throughout the town. Properties bordering the preserve or adjacent to bay wetlands see consistent tick pressure from spring through fall.",
    areas: ["Massapequa Preserve border properties", "South Oyster Bay adjacent neighborhoods", "Massapequa Park residential streets", "North Massapequa community areas", "Seaford border properties"],
    nearbyTowns: ["seaford", "babylon", "amityville", "north-massapequa", "farmingdale"],
  },
];

export function getTownBySlug(slug: string): TownData | undefined {
  return TOWNS.find((t) => t.slug === slug);
}

export const SUFFOLK_TOWNS_DATA = TOWNS.filter((t) => t.county === "Suffolk");
export const NASSAU_TOWNS_DATA = TOWNS.filter((t) => t.county === "Nassau");
